module.exports = {
  // users pts
  pts: {
    max: 93,
    tema: 61,
    fedya: 79,
    barca: 80,
    jane: 74,
    nina: 79,
    sveta: 90,
    pasha: 83,
    gleb: 90,
    polly: 67,
    anya: 44,
    samu: 79,
    jane_jr: 45,
    vera: 53,
    dante: 48,
    bd: 71,
    mario: 48,
    vlad2: 50,
    max2: 54,
  },

  // users flow
  flow: {
    max: "",
    tema: "",
    fedya: "➘1",
    barca: "➘1",
    jane: "➘1",
    nina: "➚2",
    sveta: "➘1",
    pasha: "",
    gleb: "➚1",
    polly: "",
    anya: "",
    samu: "➘1",
    jane_jr: "",
    vera: "➚1",
    dante: "➘1",
    bd: "➚1",
    mario: "➚2",
    vlad2: "➘1",
    max2: "",
  },

  // users ID
  id: {
    max: "ecstvzz",
    tema: "temasafonov",
    fedya: "Amblig",
    barca: "vladoosssssss",
    jane: "JanineErofeeva",
    nina: "nbulavina",
    sveta: "antonets_svetlana",
    pasha: "pavelfedotov99",
    gleb: "Glebporotikov",
    polly: "PolinaPorotikova",
    anya: "anna_alekseevna2206",
    samu: "Evillcola",
    jane_jr: "eva_4li",
    vera: "V_SV06",
    dante: "jdlegendary",
    bd: "krofly03",
    max2: "maximqa",
    vlad2: "SteshVA",
    mario: "Mincer2412",
    ox: "oxxana0",
  },
};
